newfikle

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -4,50 +4,51 @@ env:
   variables:
     AWS_ACCOUNT_ID: "612565767098"
     AWS_DEFAULT_REGION: "ap-south-1"
+    DOCKER_USERNAME: "AWS"
+    PROJECT_NAME: "ror-app"
     RAILS_REPO: "rails"
     NGINX_REPO: "nginx"
-    PROJECT_NAME: "ror-app"
 
 phases:
-  install:
-    runtime-versions:
-      ruby: 2.6
-    commands:
-      - echo Installing Docker...
-      - yum install -y docker
-      - service docker start
-      - echo Logging in to Amazon ECR...
-      - aws --version
-      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
-
   pre_build:
     commands:
-      - echo Build started on `date`
-      - echo Creating ECR repositories if they don't exist
-      - aws ecr describe-repositories --repository-names "$RAILS_REPO" || aws ecr create-repository --repository-name "$RAILS_REPO"
-      - aws ecr describe-repositories --repository-names "$NGINX_REPO" || aws ecr create-repository --repository-name "$NGINX_REPO"
-      - echo Getting Git commit hash
-      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
-      - echo "Using image tag: ${COMMIT_HASH:-latest}"
-      - IMAGE_TAG=${COMMIT_HASH:-latest}
+      - echo "Checking Docker installation..."
+      - |
+        if ! command -v docker &> /dev/null; then
+          echo "Docker not found, installing..."
+          yum update -y
+          yum install -y docker
+          service docker start
+          usermod -a -G docker ec2-user
+        fi
+      - echo "Logging in to ECR..."
+      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username $DOCKER_USERNAME --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
+      - echo "Pre-build phase complete"
 
   build:
     commands:
-      - echo Building Rails Docker image...
-      - docker build -t $RAILS_REPO:latest -f Dockerfile .
-      - docker tag $RAILS_REPO:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$RAILS_REPO:$IMAGE_TAG
-      - echo Building Nginx Docker image...
-      - docker build -t $NGINX_REPO:latest -f docker/nginx/Dockerfile .
-      - docker tag $NGINX_REPO:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$NGINX_REPO:$IMAGE_TAG
+      - echo "Building Docker images..."
+      - docker build -t $RAILS_REPO -f docker/app/Dockerfile .
+      - docker build -t $NGINX_REPO -f docker/nginx/Dockerfile .
+      - echo "Docker build phase complete"
 
   post_build:
     commands:
-      - echo Pushing Rails image...
-      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$RAILS_REPO:$IMAGE_TAG
-      - echo Pushing Nginx image...
-      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$NGINX_REPO:$IMAGE_TAG
-      - echo Build completed on `date`
+      - echo "Tagging and pushing Docker images to ECR..."
+      - docker tag $RAILS_REPO:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$RAILS_REPO:latest
+      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$RAILS_REPO:latest
+      - docker tag $NGINX_REPO:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$NGINX_REPO:latest
+      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$NGINX_REPO:latest
+      - echo "Docker images pushed successfully"
+      - echo "Creating imagedefinitions.json for ECS..."
+      - printf '[{"name":"%s","imageUri":"%s"},{"name":"%s","imageUri":"%s"}]' \
+          $RAILS_REPO \
+          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$RAILS_REPO:latest \
+          $NGINX_REPO \
+          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$NGINX_REPO:latest \
+        > imagedefinitions.json
+      - echo "imagedefinitions.json created"
 
 artifacts:
   files:
-    - '**/*'
+    - imagedefinitions.json
